CREATE TABLE bucketlistitem (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    parent_id INTEGER,
    FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE SET NULL
);

CREATE TABLE bucketlistitem_categories (
    bucketlistitem_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    FOREIGN KEY (bucketlistitem_id) REFERENCES bucketlistitem(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);
